apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: hello-api-deployment
spec:
  selector:
    matchLabels:
      app: hello-api
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: hello-api
    spec:
      containers:
      - name: hello-api
        image: diegofernandes/k8s-facef:0.0.3
        command: ["/bin/app"]
        args: ["--config", "$(CONFIG_FILE)"]
        ports:
        - containerPort: 8080
        env:
          # Define the environment variable
          - name: PORT # Notice that the case is different here
                                       # from the key name in the ConfigMap.
            valueFrom:
              configMapKeyRef:
                name: hello-api-config          # The ConfigMap this value comes from.
                key: port # The key to fetch.
          - name: CONFIG_FILE
            valueFrom:
              configMapKeyRef:
                name: hello-api-config
                key: config_file
        volumeMounts:
        - name: config
          mountPath: "/config"
          readOnly: true
      volumes:
      # You set volumes at the Pod level, then mount them into containers inside that Pod
      - name: config
        configMap:
          # Provide the name of the ConfigMap you want to mount.
          name: hello-api-config
          # An array of keys from the ConfigMap to create as files
          items:
          - key: "hello-api.yaml"
            path: "hello-api.yaml"